name: CI

defaults:
  run:
    shell: bash
    working-directory: MovieDatabase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-

      - name: Cache Mint packages
        uses: actions/cache@v2
        with:
          path: ${{ env.MINT_PATH }}
          key: ${{ runner.os }}-mint-${{ hashFiles('Mintfile') }}
          restore-keys: ${{ runner.os }}-mint-

      - name: Install bundler
        run: | 
          gem install bundler --no-document
          bundle config set deployment 'true';
          bundle config path vendor/bundle;
          bundle install

      - name: Install mint
        run: |
          brew upgrade
          brew install mint
          mint bootstrap

      - name: Setup ApiKey.swift
        run: cp _ApiKey.swift ApiKey.swift

      - name: Change Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_12.2.app

      - name: Run tests
        run: bundle exec fastlane test
      
    env:
      MINT_PATH: ${{ github.workspace }}/mint